# Generated by Django 4.0.2 on 2022-02-18 22:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('time_begin', models.DateField()),
                ('time_end', models.DateField()),
                ('show_only_years', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('finished', models.BooleanField(default=False)),
                ('finished_title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('proficency', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperiences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('time_begin', models.DateField()),
                ('time_end', models.DateField()),
                ('show_only_years', models.BooleanField(default=False)),
                ('internship', models.BooleanField(default=False)),
                ('current', models.BooleanField(default=False)),
                ('description', models.TextField()),
            ],
        ),
    ]
