# Generated by Django 4.0.2 on 2022-02-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_workexperiences_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='location',
            field=models.CharField(default='None', max_length=255),
            preserve_default=False,
        ),
    ]
