# Generated by Django 4.0.2 on 2022-02-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_education_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='category',
            field=models.CharField(choices=[('programming', 'Programming'), ('sysadmin', 'Sysadmin'), ('other', 'Other')], default='other', max_length=255),
            preserve_default=False,
        ),
    ]
