# Generated by Django 4.0.2 on 2022-02-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_skills_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='category',
            field=models.CharField(choices=[('programming', 'Programming'), ('sysadmin', 'Sysadmin'), ('other', 'Other'), ('languages', 'Languages')], max_length=255),
        ),
    ]
